[project]
name = "kgsim"
version = "0.1.3"
description = "A library to interact with simulations with."
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"
